
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DOWN FILLER FORMATION LOCATION_SIDE LOCATION_YARDAGE PASS_DIRECTION PASS_LENGTH PLAYER TACKLER TIME TYPE YARDAGE\n    play : pass\n    \n    pass : DOWN location TIME FORMATION PLAYER TYPE direction FILLER PLAYER FILLER location FILLER YARDAGE TACKLER\n    \n    direction : PASS_LENGTH PASS_DIRECTION\n    \n    location : LOCATION_SIDE LOCATION_YARDAGE\n    '
    
_lr_action_items = {'DOWN':([0,],[3,]),'$end':([1,2,20,],[0,-1,-2,]),'LOCATION_SIDE':([3,16,],[5,5,]),'TIME':([4,7,],[6,-4,]),'LOCATION_YARDAGE':([5,],[7,]),'FORMATION':([6,],[8,]),'FILLER':([7,11,14,15,17,],[-4,13,-3,16,18,]),'PLAYER':([8,13,],[9,15,]),'TYPE':([9,],[10,]),'PASS_LENGTH':([10,],[12,]),'PASS_DIRECTION':([12,],[14,]),'YARDAGE':([18,],[19,]),'TACKLER':([19,],[20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'play':([0,],[1,]),'pass':([0,],[2,]),'location':([3,16,],[4,17,]),'direction':([10,],[11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> play","S'",1,None,None,None),
  ('play -> pass','play',1,'p_play','fray_pdf.py',78),
  ('pass -> DOWN location TIME FORMATION PLAYER TYPE direction FILLER PLAYER FILLER location FILLER YARDAGE TACKLER','pass',14,'p_pass','fray_pdf.py',84),
  ('direction -> PASS_LENGTH PASS_DIRECTION','direction',2,'p_direction','fray_pdf.py',97),
  ('location -> LOCATION_SIDE LOCATION_YARDAGE','location',2,'p_location','fray_pdf.py',102),
]
